version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: smartqueue-postgres
    environment:
      POSTGRES_USER: smartqueue
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartqueue_db
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smartqueue_net

  redis:
    image: redis:7-alpine
    container_name: smartqueue-redis
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - smartqueue_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: smartqueue-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - smartqueue_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: smartqueue-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - smartqueue_net

  smartqueue-backend:
    build:
      context: ./smartqueue-backend
    container_name: smartqueue-backend
    ports:
      - "18080:8080"
    depends_on:
      - postgres
      - kafka
    networks:
      - smartqueue_net
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smartqueue_db
      - TZ=Asia/Kolkata

volumes:
  postgres_data:
  redis_data:

networks:
  smartqueue_net:
    driver: bridge
